//
//  TourOfLocations.swift
//  bustedMachine
//
//  Created by Marty Hernandez Avedon on 09/30/17.
//  Copyright © 2017 Marty's . All rights reserved.
//

import Foundation

// MARK: - Area 1

let weedyField = Node(location: "Weedy Field", description: "You are standing in a weedy field. The GRASS comes up to your ankles. It grows in irregular tufts, interrupted here and there by CLOVER.", objects: [Grass.name: Grass, Clover.name: Clover, Weeds.name: Weeds])
let nearHighway = Node(location: "Near Highway", description: "You are standing on the shoulder of an enormous highway. It's very empty and very quiet. Occassionally, a convoy passes by, one huge TRUCK after another...", objects: [Truck.name: Truck])
let farHighway = Node(location: "Far Highway", description: "You are standing on the shoulder of an enormous highway. It goes on and on, in a long curve, toward a cluster of LIGHTS.", objects: [Lights.name: Lights, Truck.name: Truck])
let fartherHighway = Node(location: "Farther Highway", description: "You are standing on the shoulder of an enormous highway. It goes on and on, in a long curve, toward a cluster of LIGHTS. Through the mist, you can just barely make out an enormous SPIRE that rises endlessly into the sky.", objects: [Lights.name: Lights, Truck.name: Truck, Spire.name: Spire])
let farthestHighway = Node(location: "Farthest Highway", description: "You are standing on the shoulder of an enormous highway. It goes on and on, in a long curve, toward a cluster of LIGHTS. You can clearly see an enormous SPIRE. It seems to split the sky in two. Walking this slowly, you won't be seeing more of it any time soon...\n\nYou sure wish you could USE a vehicle to get there.", objects: [Lights.name: Lights, Truck.name: Truck, Spire.name: Spire])
let forest = Node(location: "Forest", description: "You are at the edge of a deep forest. The TREES are black and bare. GRASS and CLOVER grow in erratic patterns. Scattered about are filthy plastic BAGS, crumpled vinyl SKINS, and jagged machine PARTS.", objects: [Trees.name: Trees, Grass.name: Grass, Clover.name: Clover, Bags.name: Bags, Parts.name: Parts, Skins.name: Skins])
let deepForest = Node(location: "Deep Forest", description: "You are standing in a deep forest. It's difficut to move because you are almost completely surrounded by tall WEEDS, ragged pieces of TRASH, and skinny black TREES. Your fuzz is getting snagged on everything.", objects: [Trees.name: Trees, Trash.name: Trash, Weeds.name: Weeds])
let clearing = Node(location: "Clearing", description: "You are standing in a strange clearing. Dense TREES surround you on all sides. The ground drops down abruptly. The soil has been washed away, revealing beige TILES covered in a loose tangle of off-white FIBERS. A thin layer of water coats everything.", objects: [Tiles.name: Tiles, Trees.name: Trees, Fibers.name: Fibers])
let marsh1 = Node(location: "Far Marsh", description: "You are standing in a squishy field. The ground is very wet and spongy. Shiny strips of vinyl SKIN are scattered around, hanging from tall WEEDS and broken black TREES.", objects: [Skin.name: Skin, Weeds.name: Weeds, Trees.name: Trees])
let werewolfPark = Node(location: "Werewolf Park", description: "You are standing in a mucky forest. Bare black TREES grow in loose arrangements. The ground is covered in tall GRASS, CLOVER, and scratchy WEEDS. There are also many recently felled TREES. These LOGS provide dry footing and can be USED as a place to sit.", objects: [Logs.name: Logs, Trees.name: Trees, Grass.name: Grass, Clover.name: Clover, Weeds.name: Weeds], npcs: [Werewolf.name: Werewolf])
let marsh2 = Node(location: "Near Marsh", description: "You are standing in a squishy field. The ground is very wet and spongy. Shiny strips of vinyl SKIN are scattered around, hanging from tall WEEDS and broken black TREES.", objects: [Trees.name: Trees, Skin.name: Skin, Weeds.name: Weeds])
let abandonedLot = Node(location: "Abandoned Lot", description: "You are standing in an abandoned lot. It is surrounded on all sides by a chain link FENCE. The ground is made up of beige TILES. There are outlets for charging electric bikes along a low guard RAIL. An overflowing TRASH CAN stands near the entrance.", objects: [TrashCan.name: TrashCan, Trash.name: Trash, ScoobySnacks.name: ScoobySnacks, Tiles.name: Tiles, GuardRail.name: GuardRail, Fence.name: Fence])
let gate = Node(location: "Gate", description: "You stand before a GATE. It is part of a chainlink FENCE. One side of the FENCE is reinforced by a long metal guard RAIL with wires coming out of it.", objects: [GuardRail.name: GuardRail, Fence.name: Fence, Gate.name: Gate])
let porchOfAShotgunshack = Node(location: "Porch of A Shotgun Shack", description: "You find yourself standing in front of a SHOTGUN SHACK. It looks very weathered. A heavy LOCK is attached to the door. Someone has spraypainted the words 'Monster Party' and a crude DRAWING of a googly-eyed monster across the front porch.", objects: [ShotgunShack.name: ShotgunShack, Drawing.name: Drawing, Lock.name: Lock])
let frontroom = Node(location: "Front Room", description: "You find yourself inside a shotgun shack. The front room is vividly painted orange and green. You see a Naugahyde SOFA, a wooden coffee TABLE, a plastic beach CHAIR, and a metal CABINET with a CRT monitor inside.", objects: [Table.name: Table, Chair.name: Chair, Cabinet.name: Cabinet, CRT.name: CRT, Sofa.name: Sofa])
let bedroom = Node(location: "Bedroom", description: "You find yourself inside a shotgun shack. This narrow room is dominated by a queen-size MATTRESS that lies flat on the floor. A tangle of twinkling FAIRYLIGHTS covers the ceiling. On the MATTRESS is an ASHTRAY and some torn NAPKINS.", objects: [Fairylights.name: Fairylights, Ashtray.name: Ashtray, Napkins.name: Napkins, Mattress.name: Mattress])
let makeshiftBedroom = Node(location: "Makeshift Bedroom", description: "You find yourself inside a shotgun shack. This is a hallway that is also a bedroom. Or a bedroom that is also a hallway. There is an empty bed frame and a chest of DRAWERS. Crumpled drywall is piled by the back wall.", objects: [Drawers.name: Drawers])
let kitchen = Node(location: "Kitchen", description: "You find yourself inside a shotgun shack. This kitchen is vividly painted green and orange. Someone has spraypainted 'Humans suck!' on the wall. There is a REFRIGERATOR, and many open CABINETS. There is a big HOLE in the floor by the SINK.", objects: [Sink.name: Sink, Refrigerator.name: Refrigerator, Cabinets.name: Cabinets, Hole.name: Hole])
let bathroom = Node(location: "Bathroom", description: "You find yourself inside a shotgun shack. This is a bathroom. It is so small, you can wash your hands while still sitting on the TOILET. All the walls are covered in GRAFFITI. The mirror above the SINK is smashed.", objects: [Toilet.name: Toilet, Sink.name: Sink, Graffiti.name: Graffiti])
let laundryRoom = Node(location: "Laundry Room", description: "You find yourself inside a shotgun shack. This is a smelly, humid room made up of bare beige TILES. Pipes and wires connect to a pair of large white MACHINES. Next to the MACHINES are some plastic BOTTLES and cardboard BOXES.", objects: [Tiles.name: Tiles, Machines.name: Machines, Boxes.name: Boxes, Bottles.name: Bottles])
let basement = Node(location: "Basement", description: "You find yourself inside a shotgun shack. Down a creaky set of stairs is a musty room made up of beige TILES. Wood paneling is glued halfway up the walls. There is a POSTER of movie about an astronaut.", objects: [Tiles.name: Tiles, Poster.name: Poster])
let secondBasement = Node(location: "Second Basement", description: "You find yourself inside a shotgun shack. Down another set of creaky stairs is the second basement. It is as big as the house is long. The floor is spread with shag carpeting. Colorful GRAFFITI and stickers cover the beige TILES.\n\nYou see three Monsters sitting around a record player: COOKIEPUSS, POSSUM, and FUTURE." , objects: [Tiles.name: Tiles, Graffiti.name: Graffiti], npcs: [Cookiepuss.name: Cookiepuss, Possum.name: Possum, FutureCreep.name: FutureCreep])

// MARK: - Area 2

let cityLimits = Node(location: "City Limits", description: "You are on the city limits of Zucktown, a city named after one of the founding fathers of Twifoogle. There is a big blue sign with a thumbs up icon greeting you as you approach.")

// MARK: - Area 3

let baseOfSpire = Node(location: "Base of the Spire", description: "You travel up and up and up the long curve to the base of an enormous building that rises endlessly into the sky. If you squint, you can just barely make out the sight of another enormous spire off in the distance, as the curve continues around.")
